package com.alan.kutilssample.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.alan.kutilssample.bean.IsFirstEnterApp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IS_FIRST_ENTER_APP".
*/
public class IsFirstEnterAppDao extends AbstractDao<IsFirstEnterApp, Long> {

    public static final String TABLENAME = "IS_FIRST_ENTER_APP";

    /**
     * Properties of entity IsFirstEnterApp.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property IsFirstEnterApp = new Property(1, boolean.class, "isFirstEnterApp", false, "IS_FIRST_ENTER_APP");
    }


    public IsFirstEnterAppDao(DaoConfig config) {
        super(config);
    }
    
    public IsFirstEnterAppDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IS_FIRST_ENTER_APP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: Id
                "\"IS_FIRST_ENTER_APP\" INTEGER NOT NULL );"); // 1: isFirstEnterApp
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IS_FIRST_ENTER_APP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, IsFirstEnterApp entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
        stmt.bindLong(2, entity.getIsFirstEnterApp() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, IsFirstEnterApp entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
        stmt.bindLong(2, entity.getIsFirstEnterApp() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public IsFirstEnterApp readEntity(Cursor cursor, int offset) {
        IsFirstEnterApp entity = new IsFirstEnterApp( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.getShort(offset + 1) != 0 // isFirstEnterApp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, IsFirstEnterApp entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIsFirstEnterApp(cursor.getShort(offset + 1) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(IsFirstEnterApp entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(IsFirstEnterApp entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(IsFirstEnterApp entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
